name: CI with Allure Report

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests (headless)
        run: mvn -B -Dheadless=true clean test

      - name: Build Allure HTML report
        run: |
          mvn io.qameta.allure:allure-maven:report \
            -Dallure.results.directory=allure-results \
            -Dallure.report.directory=allure-report

      - name: Upload raw Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload report to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:
    needs: test-and-report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
